[project]
name = "knnbm25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "polars>=1.24.0",
    "streamlit>=1.42.2",
]
